name: Prettier

on:
    push:
        branches: [main]

jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Format
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: index.json --write --tab-width 4 --print-width 1
                  commit_message: "chore: format json"
                  commit_options: --author="free-domains-bot <bot@freesubdomains.org>"
                  github_token: ${{ secrets.BOT }}
